version: '3.8'

services:
  whisper-api:
    build: .
    image: whisper-api:latest
    container_name: whisper-api
    ports:
      - "8000:8000"
    environment:
      # Whisper Configuration
      - WHISPER_MODEL=large-v3
      - WHISPER_DEVICE=cuda
      - WHISPER_COMPUTE_TYPE=float16
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MAX_AUDIO_FILE_SIZE_MB=25
      # GPU Configuration
      - CUDA_VISIBLE_DEVICES=0
      - GPU_MEMORY_FRACTION=0.9
      # Performance
      - ENABLE_MODEL_CACHE=true
      - MODEL_CACHE_DIR=/app/models
    volumes:
      # Mount model cache to persist downloaded models
      - ./models:/app/models
      # Optional: Mount local .env file
      # - ./.env:/app/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge